#packmode expert

// Expert version of The Ultimate Ingot. Requires nearly all the mods from the pack to begin Ultimate production on the AFK way.
mods.extendedcrafting.TableCrafting.remove(<item:extendedcrafting:the_ultimate_ingot>); // Remove Normal Mode recipe in favor of Expert one.
mods.extendedcrafting.TableCrafting.addShaped("1c4fd00f-a70c-41b3-9d7d-db7f2aa14992", 0, <item:extendedcrafting:the_ultimate_ingot>, [
	[<item:minecraft:iron_ingot>, <item:minecraft:gold_ingot>, <item:minecraft:netherite_ingot>, <item:botania:manasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:elementium_ingot>, <item:botania:gaia_ingot>, <item:mekanism:ingot_copper>, <item:create:zinc_ingot>], 
	[<item:create:brass_ingot>, <item:eidolon:pewter_ingot>, <item:eidolon:arcane_gold_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:bigreactors:yellorium_ingot>], 
	[<item:bigreactors:cyanite_ingot>, <item:forbidden_arcanus:obsidian_ingot>, <item:industrialforegoing:pink_slime_ingot>, <item:mana-and-artifice:vinteum_ingot>, <item:mana-and-artifice:superheated_vinteum_ingot>, <item:mana-and-artifice:purified_vinteum_ingot>, <item:mana-and-artifice:superheated_purified_vinteum_ingot>, <item:mekanism:ingot_bronze>, <item:mekanism:ingot_refined_obsidian>], 
	[<item:mekanism:ingot_refined_glowstone>, <item:mekanism:ingot_steel>, <item:mekanism:ingot_osmium>, <item:mekanism:ingot_tin>, <item:mekanism:ingot_lead>, <item:mekanism:ingot_uranium>, <item:mysticalagradditions:insanium_ingot>, <item:mysticalagriculture:prosperity_ingot>, <item:mysticalagriculture:imperium_ingot>], 
	[<item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:soulium_ingot>, <item:thermal:nickel_ingot>, <item:thermal:electrum_ingot>, <item:thermal:invar_ingot>, <item:thermal:constantan_ingot>, <item:thermal:signalum_ingot>, <item:thermal:lumium_ingot>, <item:thermal:enderium_ingot>], 
	[<item:iceandfire:dragonsteel_ice_ingot>, <item:iceandfire:dragonsteel_lightning_ingot>, <item:iceandfire:ghost_ingot>, <item:tconstruct:cobalt_ingot>, <item:tconstruct:slimesteel_ingot>, <item:tconstruct:tinkers_bronze_ingot>, <item:tconstruct:rose_gold_ingot>, <item:tconstruct:pig_iron_ingot>, <item:tconstruct:queens_slime_ingot>], 
	[<item:tconstruct:manyullyn_ingot>, <item:tconstruct:hepatizon_ingot>, <item:allthemodium:allthemodium_ingot>, <item:allthemodium:unobtainium_ingot>, <item:allthemodium:vibranium_ingot>, <item:woot:si_ingot>, <item:advancedrocketry:ingottitaniumaluminide>, <item:advancedrocketry:ingottitaniumiridium>, <item:armorplus:en_netherite>], 
	[<item:astralsorcery:starmetal_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:betterendforge:aeternium_ingot>, <item:betterendforge:thallasium_ingot>, <item:betterendforge:terminite_ingot>, <item:libvulpes:ingotsilicon>, <item:psi:psimetal>, <item:libvulpes:ingotiridium>, <item:libvulpes:ingottitanium>], 
	[<item:twilightforest:knightmetal_ingot>, <item:atum:nebu_ingot>, <item:theabyss:fusioningot>, <item:theabyss:phantom_ingot>, <item:theabyss:loran_ingot>, <item:theabyss:unorithe_ingot>, <item:theabyss:netherfire_ingot>, <item:theabyss:briked_knight_ingot>, <item:theabyss:knight_ingot>]
]);