#packmode Normal

craftingTable.removeRecipe(<item:rftoolsbase:machine_frame>);
mods.extendedcrafting.TableCrafting.addShaped("1dfd07a0-ca22-4219-a00c-3d107c898ef5", 0, <item:rftoolsbase:machine_frame>, [
	[<item:bloodmagic:ritualstone>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:bloodmagic:ritualstone>], 
	[<item:rftoolsbase:dimensionalshard>, <item:bloodmagic:orbcapacityrune>, <item:bloodmagic:blankrune>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:fiery_ingot>, <item:twilightforest:knightmetal_ingot>, <item:bloodmagic:blankrune>, <item:bloodmagic:orbcapacityrune>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:bloodmagic:blankrune>, <item:theabyss:knight_ingot>, <item:theabyss:knight_ingot>, <item:twilightforest:carminite>, <item:theabyss:knight_ingot>, <item:theabyss:knight_ingot>, <item:bloodmagic:blankrune>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:twilightforest:knightmetal_ingot>, <item:theabyss:knight_ingot>, <item:appliedenergistics2:1k_cell_component>, <item:thermal:machine_frame>, <item:appliedenergistics2:1k_cell_component>, <item:theabyss:knight_ingot>, <item:twilightforest:knightmetal_ingot>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:twilightforest:fiery_ingot>, <item:twilightforest:carminite>, <item:thermal:machine_frame>, <item:industrialforegoing:machine_frame_supreme>, <item:thermal:machine_frame>, <item:twilightforest:carminite>, <item:twilightforest:fiery_ingot>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:twilightforest:knightmetal_ingot>, <item:theabyss:knight_ingot>, <item:appliedenergistics2:1k_cell_component>, <item:thermal:machine_frame>, <item:appliedenergistics2:1k_cell_component>, <item:theabyss:knight_ingot>, <item:twilightforest:knightmetal_ingot>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:bloodmagic:blankrune>, <item:theabyss:knight_ingot>, <item:theabyss:knight_ingot>, <item:twilightforest:carminite>, <item:theabyss:knight_ingot>, <item:theabyss:knight_ingot>, <item:bloodmagic:blankrune>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:bloodmagic:orbcapacityrune>, <item:bloodmagic:blankrune>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:fiery_ingot>, <item:twilightforest:knightmetal_ingot>, <item:bloodmagic:blankrune>, <item:bloodmagic:orbcapacityrune>, <item:rftoolsbase:dimensionalshard>], 
	[<item:bloodmagic:ritualstone>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:bloodmagic:ritualstone>]
]);

craftingTable.removeRecipe(<item:rftoolsbase:machine_base>);
mods.extendedcrafting.TableCrafting.addShaped("5102663a-5764-4624-87ad-4dcbb3c55b19", 0, <item:rftoolsbase:machine_base>, [
	[<item:bloodmagic:ritualstone>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:bloodmagic:ritualstone>], 
	[<item:rftoolsbase:dimensionalshard>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:thermal:lumium_glass>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:astralsorcery:glass_lens>, <item:astralsorcery:glass_lens>, <item:astralsorcery:glass_lens>, <item:astralsorcery:glass_lens>, <item:astralsorcery:glass_lens>, <item:astralsorcery:glass_lens>, <item:astralsorcery:glass_lens>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:theabyss:knight_ingot>, <item:twilightforest:fiery_ingot>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:carminite>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:fiery_ingot>, <item:theabyss:knight_ingot>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:theabyss:knight_ingot>, <item:twilightforest:fiery_ingot>, <item:thermal:machine_frame>, <item:industrialforegoing:machine_frame_advanced>, <item:thermal:machine_frame>, <item:twilightforest:fiery_ingot>, <item:theabyss:knight_ingot>, <item:rftoolsbase:dimensionalshard>], 
	[<item:rftoolsbase:dimensionalshard>, <item:theabyss:knight_ingot>, <item:twilightforest:fiery_ingot>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:carminite>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:fiery_ingot>, <item:theabyss:knight_ingot>, <item:rftoolsbase:dimensionalshard>], 
	[<item:bloodmagic:ritualstone>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:rftoolsbase:dimensionalshard>, <item:bloodmagic:ritualstone>]
]);

craftingTable.removeRecipe(<item:rftoolsdim:dimension_builder>);
mods.extendedcrafting.TableCrafting.addShaped("f03b8b5b-9b13-4a20-80e9-c4ce44e393c1", 0, <item:rftoolsdim:dimension_builder>, [
	[<item:atum:godforged_block>, <item:evilcraft:promise_speed_0>, <item:atum:anput_godforged_block>, <item:evilcraft:promise_tier_3>, <item:atum:anubis_godforged_block>, <item:evilcraft:promise_tier_3>, <item:atum:atem_godforged_block>, <item:evilcraft:promise_speed_0>, <item:atum:geb_godforged_block>], 
	[<item:evilcraft:promise_speed_0>, <item:theabyss:garnite_ingot>, <item:theabyss:garnite_ingot>, <item:theabyss:garnite_ingot>, <item:avaritia:neutronium_ingot>, <item:theabyss:unorithe_ingot>, <item:theabyss:unorithe_ingot>, <item:theabyss:unorithe_ingot>, <item:evilcraft:promise_speed_0>], 
	[<item:atum:tefnut_godforged_block>, <item:theabyss:garnite_ingot>, <item:twilightforest:carminite_block>, <item:twilightforest:carminite_block>, <item:appliedenergistics2:interface>, <item:twilightforest:alpha_fur>, <item:twilightforest:alpha_fur>, <item:theabyss:unorithe_ingot>, <item:atum:horus_godforged_block>], 
	[<item:appliedenergistics2:controller>, <item:theabyss:garnite_ingot>, <item:twilightforest:carminite_block>, <item:theabyss:enderbow>.withTag({Damage: 0 as int}), <item:appliedenergistics2:fluid_interface>, <item:theabyss:enderbow>.withTag({Damage: 0 as int}), <item:twilightforest:alpha_fur>, <item:theabyss:unorithe_ingot>, <item:appliedenergistics2:controller>], 
	[<item:atum:shu_godforged_block>, <item:avaritia:neutronium_ingot>, <item:appliedenergistics2:interface>, <item:appliedenergistics2:fluid_interface>, <item:rftoolsbase:machine_frame>, <item:appliedenergistics2:fluid_interface>, <item:appliedenergistics2:interface>, <item:avaritia:neutronium_ingot>, <item:atum:isis_godforged_block>], 
	[<item:appliedenergistics2:controller>, <item:theabyss:unorithe_ingot>, <item:twilightforest:steeleaf_ingot>, <item:theabyss:enderbow>.withTag({Damage: 0 as int}), <item:appliedenergistics2:fluid_interface>, <item:theabyss:enderbow>.withTag({Damage: 0 as int}), <item:twilightforest:carminite_block>, <item:theabyss:garnite_ingot>, <item:appliedenergistics2:controller>], 
	[<item:atum:seth_godforged_block>, <item:theabyss:unorithe_ingot>, <item:twilightforest:steeleaf_ingot>, <item:twilightforest:steeleaf_ingot>, <item:appliedenergistics2:interface>, <item:twilightforest:carminite_block>, <item:twilightforest:carminite_block>, <item:theabyss:garnite_ingot>, <item:atum:montu_godforged_block>], 
	[<item:evilcraft:promise_speed_0>, <item:theabyss:unorithe_ingot>, <item:theabyss:unorithe_ingot>, <item:theabyss:unorithe_ingot>, <item:avaritia:neutronium_ingot>, <item:theabyss:garnite_ingot>, <item:theabyss:garnite_ingot>, <item:theabyss:garnite_ingot>, <item:evilcraft:promise_speed_0>], 
	[<item:atum:ra_godforged_block>, <item:evilcraft:promise_speed_0>, <item:atum:ptah_godforged_block>, <item:evilcraft:promise_tier_3>, <item:atum:osiris_godforged_block>, <item:evilcraft:promise_tier_3>, <item:atum:nuit_godforged_block>, <item:evilcraft:promise_speed_0>, <item:atum:nepthys_godforged_block>]
]);

craftingTable.removeRecipe(<item:rftoolsbuilder:builder>);
mods.extendedcrafting.TableCrafting.addShaped("b42009d4-6764-49be-a64c-4b6164a17cfc", 0, <item:rftoolsbuilder:builder>, [
	[<item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:appliedenergistics2:charger>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>], 
	[<item:advancedrocketry:platetitaniumiridium>, <item:industrialforegoing:pink_slime_ingot>, <item:industrialforegoing:pink_slime_ingot>, <item:mekanism:steel_casing>, <item:thermal:rf_coil>, <item:mekanism:steel_casing>, <item:industrialforegoing:pink_slime_ingot>, <item:industrialforegoing:pink_slime_ingot>, <item:advancedrocketry:platetitaniumiridium>], 
	[<item:advancedrocketry:platetitaniumiridium>, <item:industrialforegoing:pink_slime_ingot>, <item:mekanism:steel_casing>, <item:thermal:rf_coil>, <item:appliedenergistics2:interface>, <item:thermal:rf_coil>, <item:mekanism:steel_casing>, <item:industrialforegoing:pink_slime_ingot>, <item:advancedrocketry:platetitaniumiridium>], 
	[<item:advancedrocketry:platetitaniumiridium>, <item:mekanism:steel_casing>, <item:thermal:rf_coil>, <item:mekanism:ultimate_fluid_tank>, <item:appliedenergistics2:fluid_interface>, <item:mekanism:ultimate_fluid_tank>, <item:thermal:rf_coil>, <item:mekanism:steel_casing>, <item:advancedrocketry:platetitaniumiridium>], 
	[<item:botania:mana_fluxfield>, <item:thermal:rf_coil>, <item:appliedenergistics2:interface>, <item:appliedenergistics2:fluid_interface>, <item:rftoolsbase:machine_frame>, <item:appliedenergistics2:fluid_interface>, <item:appliedenergistics2:interface>, <item:thermal:rf_coil>, <item:botania:mana_fluxfield>], 
	[<item:advancedrocketry:platetitaniumiridium>, <item:mekanism:steel_casing>, <item:thermal:rf_coil>, <item:mekanism:ultimate_fluid_tank>, <item:appliedenergistics2:fluid_interface>, <item:mekanism:ultimate_fluid_tank>, <item:thermal:rf_coil>, <item:mekanism:steel_casing>, <item:advancedrocketry:platetitaniumiridium>], 
	[<item:advancedrocketry:platetitaniumiridium>, <item:industrialforegoing:pink_slime_ingot>, <item:mekanism:steel_casing>, <item:thermal:rf_coil>, <item:appliedenergistics2:interface>, <item:thermal:rf_coil>, <item:mekanism:steel_casing>, <item:industrialforegoing:pink_slime_ingot>, <item:advancedrocketry:platetitaniumiridium>], 
	[<item:advancedrocketry:platetitaniumiridium>, <item:industrialforegoing:pink_slime_ingot>, <item:industrialforegoing:pink_slime_ingot>, <item:mekanism:steel_casing>, <item:thermal:rf_coil>, <item:mekanism:steel_casing>, <item:industrialforegoing:pink_slime_ingot>, <item:industrialforegoing:pink_slime_ingot>, <item:advancedrocketry:platetitaniumiridium>], 
	[<item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:fluxnetworks:gargantuan_flux_storage>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>, <item:advancedrocketry:platetitaniumiridium>]
]);

craftingTable.removeRecipe(<item:rftoolsstorage:modular_storage>);
mods.extendedcrafting.TableCrafting.addShaped("5ba87517-b42d-42e3-9a15-cfb441302f98", 0, <item:rftoolsstorage:modular_storage>, [
	[<item:compressium:redstone_4>, <item:armorplus:infused_frost_lava_crystal>, <item:armorplus:infused_frost_lava_crystal>, <item:armorplus:infused_frost_lava_crystal>, <item:compressium:redstone_4>], 
	[<item:armorplus:infused_frost_lava_crystal>, <item:woot:cell_4>, <item:enderstorage:ender_chest>, <item:woot:cell_4>, <item:armorplus:infused_frost_lava_crystal>], 
	[<item:armorplus:infused_frost_lava_crystal>, <item:ironchest:crystal_chest>, <item:rftoolsbase:machine_frame>, <item:ironchest:crystal_chest>, <item:armorplus:infused_frost_lava_crystal>], 
	[<item:armorplus:infused_frost_lava_crystal>, <item:woot:cell_4>, <item:mekanism:personal_chest>, <item:woot:cell_4>, <item:armorplus:infused_frost_lava_crystal>], 
	[<item:compressium:redstone_4>, <item:armorplus:infused_frost_lava_crystal>, <item:armorplus:infused_frost_lava_crystal>, <item:armorplus:infused_frost_lava_crystal>, <item:compressium:redstone_4>]
]);

craftingTable.removeRecipe(<item:rftoolsutility:crafter1>);
mods.extendedcrafting.TableCrafting.addShaped("f8a6e25c-7e33-4eca-8dd4-6a974aef5b8f", 0, <item:rftoolsutility:crafter1>, [
	[<item:thermal:enderium_plate>, <item:avaritia:double_compressed_crafting_table>, <item:avaritia:double_compressed_crafting_table>, <item:avaritia:double_compressed_crafting_table>, <item:thermal:enderium_plate>], 
	[<item:avaritia:double_compressed_crafting_table>, <item:tconstruct:slimesteel_block>, <item:appliedenergistics2:formation_core>, <item:tconstruct:slimesteel_block>, <item:avaritia:double_compressed_crafting_table>], 
	[<item:avaritia:double_compressed_crafting_table>, <item:betterendforge:thallasium_ingot>, <item:rftoolsbase:machine_frame>, <item:betterendforge:thallasium_ingot>, <item:avaritia:double_compressed_crafting_table>], 
	[<item:avaritia:double_compressed_crafting_table>, <item:tconstruct:slimesteel_block>, <item:appliedenergistics2:annihilation_core>, <item:tconstruct:slimesteel_block>, <item:avaritia:double_compressed_crafting_table>], 
	[<item:thermal:enderium_plate>, <item:avaritia:double_compressed_crafting_table>, <item:avaritia:double_compressed_crafting_table>, <item:avaritia:double_compressed_crafting_table>, <item:thermal:enderium_plate>]
]);